### ISSUE TITLE
Why is this unable to be decompiled?

### ISSUE THREAD

**Issue by Ekultek** [LeagueOfPoro/EsportsCapsuleFarmer#3]
Your exe that you're providing is detected by two AV's as malicious: https://www.virustotal.com/gui/file/8e9d7cb05e025962ae2f55ff514dd9580d664849b99d444f6225a130c9be1f9c/detection

When decompiling the exe in order to determine the issue myself I'm unable to decompile it, what this means is that in some way you put something into the exe to prevent the ability to decompile it and see whats going on. So my question becomes, why?

Error from decompiler:

```
Unknown type 0
Traceback (most recent call last):
  File "/home/salty/venv/bin/uncompyle6", line 8, in <module>
    sys.exit(main_bin())
  File "/home/salty/venv/lib/python3.8/site-packages/uncompyle6/bin/uncompile.py", line 196, in main_bin
    result = main(src_base, out_base, pyc_paths, source_paths, outfile,
  File "/home/salty/venv/lib/python3.8/site-packages/uncompyle6/main.py", line 304, in main
    deparsed = decompile_file(
  File "/home/salty/venv/lib/python3.8/site-packages/uncompyle6/main.py", line 201, in decompile_file
    decompile(
  File "/home/salty/venv/lib/python3.8/site-packages/uncompyle6/main.py", line 81, in decompile
    assert iscode(co), f"""{co} does not smell like code"""
AssertionError: None does not smell like code
```

As you can see the assertion itself determines that you are preventing people from reversing your app, I just would like to know why?

**Comment by JonasTD** [comment]
I assume he doesn't want people to steal the work he put into the app; just like most software that isn't "open-source"

**Comment by oldkingcone** [comment]
> I assume they don't want people to steal the work they put into the app; just like most software that isn't "open-source"

That's now how python works, or code works in general. From my experience if its obfuscated or has anti tamper techniques in the code there's something nasty in the code. Considering that multiple sandboxes have detected and consider this executable in question as behaving like ransomware, its very curious why this guy went the extra step to make sure the executable which was transpiled from python to a native binary as difficult as it is, that is a real good indication that the executable is not the same code as the small python script in this repo.

**Comment by Ekultek** [comment]
Side note: https://www.joesandbox.com/analysis/658201/0/html

**Comment by Ekultek** [comment]
Also for people reading this that don't understand, python exe files are completely decompilable. Unless you specifically design the exe to not be decompiled anyone with the tools and know-how can get the source code of the application. Now seeing how this is an "opensource" tool that has its "source code" on github. That fact is completely irrelevant.

**Comment by LordTeruki** [comment]
🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩

**Comment by LeagueOfPoro** [comment]
I did not do any measures that would prevent decompiling. The exes are created exactly as it says in the README.md. 
```
pipenv install --dev
pipenv run pyinstaller -F --icon=poro.ico .\main.py
```

**Comment by LordTeruki** [comment]
download this exe and then login to league, seems legit

**Comment by LeagueOfPoro** [comment]
This is your error message:
> File "/home/salty/venv/lib/python3.8/site-packages/uncompyle6/main.py", line 81, in decompile

The program is compiled with Python 3.10 as you can see in [Pipfile](https://github.com/LeagueOfPoro/EsportsCapsuleFarmer/blob/master/Pipfile).
You are using uncompyle6 which supports Python until 3.8. [From the PyPi.org of uncompyle6](https://pypi.org/project/uncompyle6/): 
>  It accepts bytecodes from Python version 1.0 to version 3.8, spanning over 24 years of Python releases. 

So my recommendation - if you don't know how to decompile files and cannot be bothered reading the documentation for tools you are using, maybe it is not a great idea to accuse and attack others

**Comment by LeagueOfPoro** [comment]
> Side note: https://www.joesandbox.com/analysis/658201/0/html

As you can see in the sandbox, none of the code is flagged as malicious except possibly the `chromedriver.exe`. This file is downloaded when the program is run because it needs to match the Chrome version exactly. The path to the file is shown in the sandbox report, it will be somewhere in `C:\Users\<YOUR_USERNAME>\AppData\Local\Temp\`.  Here's the[ VirusTotal report](https://www.virustotal.com/gui/file/6d34426a7645f1a9e26f573ee41376d52abc71f59e47bfe1414e3bf71afad05f) of said file.

**Comment by LordTeruki** [comment]
i will also submit to AV vendors as malicious

**Comment by oldkingcone** [comment]
![image](https://user-images.githubusercontent.com/11233163/177629424-4cd80309-bb11-43da-ab2c-c509abd2772f.png)


because he put anti vm stuff in there. but its still pretty shit tbh.

**Comment by Ekultek** [comment]
maybe we should reopen this then?

**Comment by oldkingcone** [comment]
> maybe we should reopen this then?

oh 100%

**Comment by LeagueOfPoro** [comment]
You know what, I don't care anymore. You clearly don't know what you are doing and trying to find sensations somewhere where they aren't.

**Comment by LordTeruki** [comment]
you are distributing malware

**Comment by Ekultek** [comment]
https://www.virustotal.com/gui/file/8e9d7cb05e025962ae2f55ff514dd9580d664849b99d444f6225a130c9be1f9c VT disagrees with your statement now.

> You know what, I don't care anymore. You clearly don't know what you are doing and trying to find sensations somewhere where they aren't.

**Comment by LordTeruki** [comment]
until you explain, we will do our best to get this flagged by all AV vendors to stop the spread of your malware, everything you have said has been sus af

**Comment by JonasTD** [comment]
https://www.hybrid-analysis.com/sample/8e9d7cb05e025962ae2f55ff514dd9580d664849b99d444f6225a130c9be1f9c/62c5044190be191ec04b8683

**Comment by LordTeruki** [comment]
75/100 threat score YT should shut down his channel

**Comment by LordTeruki** [comment]
yeah so what?

**Comment by JonasTD** [comment]
Basically from my findings the program goes to great lengths to stop any decompiling.
It uses an api to detect if a debugger is being ran. (IsDebuggerPresent)(anti_dbg)
It detects if USB devices are connected as a way to identify possible VMware usage.
It makes use of the same strings some data grabbers such as discordtokengrabber.

It does a lot IMO more than just the intended program makes out to be.

**Comment by JonasTD** [comment]
https://www.filescan.io/uploads/62c5fc8ed10613c3c96bbc2b/reports/5b19b930-4d07-4646-b0ec-558737d19afd/overview

**Comment by Ekultek** [comment]
@JonasTD when you build the source with pyinstaller its 6.9k kb in size the release is 7.4k kb

**Comment by LeagueOfPoro** [comment]
So I had some fun. See this analysis from your "PROFESSIONAL TOOL"
https://analyze.intezer.com/analyses/752efa93-8fc7-49b8-9349-493b802103d7

It's this code:
```
from pprint import pprint
pprint("Hello world")
```

Hello world. So malicious. You security bros :D

**Comment by LeagueOfPoro** [comment]
And this is literally an empty file with no user code inside:
https://analyze.intezer.com/analyses/8f75e4d5-b861-46a0-bfc1-8b700eda7633

**Comment by auroraisluna** [comment]
# What am I reading?

> [](url ![malicous](https://user-images.githubusercontent.com/55810279/177635156-2ae824fd-ea2c-47ba-9adb-92258414ea87.PNG) )
> 
> MALICOUS says it right there

@LordTeruki 

> ![image](https://user-images.githubusercontent.com/11233163/177629424-4cd80309-bb11-43da-ab2c-c509abd2772f.png)
> 
> because he put anti vm stuff in there. but its still pretty shit tbh.

@oldkingcone 

I'm sorry but if I told you python is used to make literally ANY type of malware from ransomware to discord token grabbers, does that make any project using Python a malware as well? 
No.

Create an empty python file, compile using the same technique in the readme.md and upload to your 'security analysis tools' that you use. 
See for your self and at the same time laugh at your self for miss-using these 'credible' sites. 

The fact that you are just looking at random sites that you have **0** ideas how they work or how they analyze the code just to come up with the conclusion that its malware, just only shows you are commenting here to go into a witch hunt and provide no actual context or any usefulness to the initial issue inquiry or you have no idea of what you are doing or both. 

--

@Ekultek I see you attempted to decompile the file but you actually failed to realize you are decompiling a Python file that was built into an exe which includes Python it self and DEPENDANCIES. 
Incase you live under a rock, let me remind you that DEPENDANCIES are hosted ONLINE on PIP and updated by their publishers at ANY point in time. 
In addition to that, any developer can use other dependencies inside his own PIP package and the point is, any dependency can have some short of actual malicious code or code that can be exploited to make it malicious, example 0 Day exploits. 
It is impossible for the ordinary user to know of these exploits which is why software get updated, and obviously any credible tool online will report of them beforehand (example Dependabot by GitHub). 

You can also take a look at this article ['Famous npm package deletes files to protest Ukraine war'](https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/) to get an idea of what I mean.

Finally, you can check the repo on the most famous, professional and actually credible tool on GitHub 
https://lgtm.com/projects/g/LeagueOfPoro/EsportsCapsuleFarmer/

# Conclusion

If you are concerned a repository is a virus, look at the source code. You think a release is a virus? Find credible proof that is and report it to GitHub. Then the actual experts can take a look and come to their own conclusion. 
  
If you are looking to start drama, go to [Twitter](https://i.kym-cdn.com/entries/icons/original/000/040/828/cover6.jpg) and get off this platform.

**Comment by auroraisluna** [comment]
@Ekultek 
> Woah that's crazy.
> 
> ```
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_x64__qbz5n2kfra8p0\lib\dis.py", line 553, in <module>
>     _test()
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_x64__qbz5n2kfra8p0\lib\dis.py", line 549, in _test
>     code = compile(source, args.infile.name, "exec")
> ValueError: source code string cannot contain null bytes
> ```
> 
> Tell me again how I'm wrong. Actually don't, just install it please.

Lots of different people have installed the project, my self included. I have also decompiled the project the moment you brought up this thread to make sure, and I can decompile it just fine using https://github.com/zrax/pycdc and you can see some of the output here
![WindowsTerminal_yOHgtqdHOq](https://user-images.githubusercontent.com/98479040/177837996-6e72d3e3-34a3-4d24-bc70-5cc1ffbbecd7.png)
You can go ahead and make and run pycdc your self to see the full code.

> @SkinSpotlights `Going to preface this with, if this truly is a virus I doubt it was intentional and probably more a cause of libraries getting infected without knowledge of it happening.` That's completely acceptable and makes sense to me. Thank you.

Now that you also can see I can decompile it just fine, let's not continue this witch hunting thread then? 
If you can't build the project on your machine, contact me directly. 

@oldkingcone 
> think you need to look up how hashes are calculated using the Secure Hashing Algorithm(SHA) and then come back.

Very relevant. 

> Although likely, the fact the executable was padded by either NOP's (`\x90` ) or NULLS(`\x00`) fails to explain why if the code is truly the same as whats in the repo, is even in the trans-piled file to begin with. The extra steps done to prevent the de-compilation would indicate that the executable is not the same code as whats listed in this repo at all.
> 
> It also fails to explain why the sandboxes and AV vendors are flagging it as malicious, similarities are one thing for sure, however this does not explain behavioral flagging, which is why AV/EDR vendors are flagging it, on behavior. This culminated with the padding done to the file, does not give credence to the "oh it might just be a malicious library" theory. The reason why things like OpenProcessToken and IsDebuggerPresent are considered bad, are due to what follow on actions are typically done. The anti debugging and VM detection also do not give credence to, any of what you are saying, as that is not part of pyinstaller by any means.

Your decompiler errors or can't decompile **!=** the project is malicious or its hiding its source code.
